site_name: Squad 2

theme:
  name: material

nav:
   - Documentação:
      - Visão do Produto e Projeto: "visao.md"
      - Backlog: 
        - Backlog Geral: "backlog-safe.md"
        - Backlog ConectaFGA: "backlog-conectafga.md"
      - MVPS: "mvps.md"
      - URPS+: "urps.md"
      - PBB & BDD: "pbb.md"
      - USM: "usm.md"
      - Casos de Uso: "uml.md"
  - Entregas:
      - Unidade 1:
          - Visão Geral do Produto: "entrega-visao.md"
          - Material do Seminario - OpenUp/AUP: "entrega-seminario.md"
      - Unidade 2: "entrega-unidade-2.md"
      - Unidade 3: "entrega-unidade-3.md"
      - Unidade 4: "entrega-unidade-4.md"